import * as XLSX from 'xlsx';

/**
 * Export data array to Excel (.xlsx)
 */
export function exportToExcel(data: Record<string, any>[], filename: string, sheetName: string = 'Sheet1'): void {
  if (!data || data.length === 0) {
    alert('No data available to export');
    return;
  }
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
  XLSX.writeFile(workbook, `${filename}.xlsx`);
}

/**
 * Export data array to CSV (.csv)
 */
export function exportToCSV(data: Record<string, any>[], filename: string): void {
  if (!data || data.length === 0) {
    alert('No data available to export');
    return;
  }
  const worksheet = XLSX.utils.json_to_sheet(data);
  const csvOutput = XLSX.utils.sheet_to_csv(worksheet);
  const blob = new Blob(['\uFEFF' + csvOutput], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Printable Document Generator using Clean Media Print HTML
 */
export function printTableData(title: string, subtitle: string, headers: string[], rows: (string | number)[][]): void {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Popup is blocked, please allow popups for printing');
    return;
  }

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 20px; color: #1e293b; }
          .header { text-align: center; border-bottom: 2px solid #0284c7; padding-bottom: 12px; margin-bottom: 20px; }
          .header h1 { margin: 0; font-size: 22px; color: #0f172a; }
          .header p { margin: 4px 0 0 0; font-size: 13px; color: #64748b; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 12px; }
          th, td { border: 1px solid #cbd5e1; padding: 8px 10px; text-align: left; }
          th { background-color: #f1f5f9; font-weight: 600; color: #0f172a; }
          tr:nth-child(even) { background-color: #f8fafc; }
          .footer { margin-top: 30px; text-align: right; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
          @media print {
            body { padding: 0; }
            th { background-color: #f1f5f9 !important; -webkit-print-color-adjust: exact; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title}</h1>
          <p>${subtitle} • ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
        </div>
        <table>
          <thead>
            <tr>
              ${headers.map(h => `<th>${h}</th>`).join('')}
            </tr>
          </thead>
          <tbody>
            ${rows.map(row => `<tr>${row.map(cell => `<td>${cell !== undefined && cell !== null ? String(cell) : '-'}</td>`).join('')}</tr>`).join('')}
          </tbody>
        </table>
        <div class="footer">
          Generated by Digital Seva CSC System • Total Records: ${rows.length}
        </div>
        <script>
          window.onload = function() {
            window.print();
            setTimeout(function() { window.close(); }, 500);
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}

/**
 * Universal Auto-detecting Excel Parser (.xlsx, .xls, .csv)
 */
export interface ExcelParseResult {
  rows: Record<string, any>[];
  rejected: Array<{ rowNumber: number; data: Record<string, any>; reason: string }>;
  detectedColumns: string[];
}

export async function parseExcelFile(file: File): Promise<ExcelParseResult> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = (e) => {
      try {
        const buffer = e.target?.result;
        const workbook = XLSX.read(buffer, { type: 'array', cellDates: true });
        const firstSheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[firstSheetName];
        
        // Parse sheet to array of raw objects
        const rawRows: Record<string, any>[] = XLSX.utils.sheet_to_json(worksheet, { defval: '' });

        if (rawRows.length === 0) {
          resolve({ rows: [], rejected: [], detectedColumns: [] });
          return;
        }

        const detectedColumns = Object.keys(rawRows[0] || {});
        const processedRows: Record<string, any>[] = [];
        const rejected: Array<{ rowNumber: number; data: Record<string, any>; reason: string }> = [];

        rawRows.forEach((rawRow, idx) => {
          const rowNum = idx + 2; // header is row 1
          
          // Normalize column keys for standard access
          const normalized: Record<string, any> = {};
          
          Object.entries(rawRow).forEach(([key, val]) => {
            const rawKeyStr = key.toString().trim();
            const cleanKey = rawKeyStr.toLowerCase();
            const sanitizedKey = cleanKey.replace(/[^a-z0-9\u0900-\u097f]/g, '');

            // Convert value to string or clean number/date
            let cleanVal: string = '';
            if (val instanceof Date) {
              cleanVal = val.toISOString().split('T')[0];
            } else if (typeof val === 'number') {
              cleanVal = String(val).trim();
            } else if (typeof val === 'string') {
              cleanVal = val.trim();
            } else if (val !== null && val !== undefined) {
              cleanVal = String(val).trim();
            }

            // 1. Application Number Detection
            const isAppNoKey = 
              ['applicationnumber', 'applicationno', 'appno', 'applno', 'applicationid', 'appid', 'application', 
               'appnumber', 'ackno', 'acknowledgementno', 'acknowledgementnumber', 'receiptno', 'refno', 'referenceno', 
               'regno', 'registrationno', 'registrationnumber', 'आवेदनसंख्या', 'रसीदसंख्या', 'आवेदननं', 'आवेदनसं', 'आवेदनक्रमांक'].includes(sanitizedKey) ||
              (sanitizedKey.includes('application') && (sanitizedKey.includes('no') || sanitizedKey.includes('num') || sanitizedKey.includes('id'))) ||
              (sanitizedKey.includes('app') && (sanitizedKey.includes('no') || sanitizedKey.includes('num') || sanitizedKey.includes('id'))) ||
              (sanitizedKey.includes('ack') && (sanitizedKey.includes('no') || sanitizedKey.includes('num'))) ||
              (sanitizedKey.includes('ref') && (sanitizedKey.includes('no') || sanitizedKey.includes('num')));

            const isSrNoKey = ['srno', 'sno', 'slno', 'serialno', 'serialnumber', 'क्रमांक'].includes(sanitizedKey);

            if (isAppNoKey) {
              normalized.applicationNo = cleanVal;
              normalized.applicationNumber = cleanVal;
              normalized.appNo = cleanVal;
            } else if (isSrNoKey) {
              normalized.srNo = cleanVal;
            }
            // 2. Name detection
            else if (['applicantname', 'studentname', 'name', 'candidatename', 'fullname', 'आवेदककानाम', 'छात्रकानाम', 'नाम', 'आवेदक'].includes(sanitizedKey) || sanitizedKey.includes('applicant') || sanitizedKey.includes('student')) {
              normalized.applicantName = cleanVal;
              normalized.studentName = cleanVal;
              normalized.name = cleanVal;
            }
            // 3. Father name detection
            else if (['fathername', 'fathersname', 'father', 'husbandname', 'guardian', 'guardianname', 'पिताकानाम', 'पितापतिकानाम', 'पिता', 'अभिभावक'].includes(sanitizedKey) || sanitizedKey.includes('father') || sanitizedKey.includes('guardian')) {
              normalized.fatherName = cleanVal;
            }
            // 4. PAN Number
            else if (['pannumber', 'panno', 'pan', 'पैननंबर', 'पैनसंख्या'].includes(sanitizedKey) || sanitizedKey.includes('pan')) {
              normalized.panNumber = cleanVal;
            }
            // 5. Roll No / Course / Institution
            else if (['rollno', 'rollnumber', 'अनुक्रमांक', 'रोलनंबर'].includes(sanitizedKey) || sanitizedKey.includes('roll')) {
              normalized.rollNo = cleanVal;
            } else if (['course', 'class', 'पाठ्यक्रम', 'कक्षा'].includes(sanitizedKey) || sanitizedKey.includes('course') || sanitizedKey.includes('class')) {
              normalized.course = cleanVal;
            } else if (['institution', 'institutionname', 'college', 'collegename', 'school', 'schoolname', 'संस्थान', 'विद्यालय', 'कॉलेज'].includes(sanitizedKey) || sanitizedKey.includes('institution') || sanitizedKey.includes('college')) {
              normalized.institutionName = cleanVal;
            }
            // 6. Mobile
            else if (['mobile', 'mobileno', 'mobilenumber', 'phone', 'phoneno', 'contact', 'contactno', 'मोबाइल', 'फ़ोन', 'संपर्क'].includes(sanitizedKey) || sanitizedKey.includes('mobile') || sanitizedKey.includes('phone') || sanitizedKey.includes('contact')) {
              normalized.mobile = cleanVal;
            }
            // 7. Aadhaar
            else if (['aadhaar', 'aadhaarno', 'aadhar', 'aadharno', 'uid', 'uidai', 'आधार', 'आधारसंख्या'].includes(sanitizedKey) || sanitizedKey.includes('aadhaar') || sanitizedKey.includes('aadhar')) {
              normalized.aadhaar = cleanVal;
            }
            // 8. DOB
            else if (['dob', 'dateofbirth', 'birthdate', 'जन्मतिथि'].includes(sanitizedKey) || sanitizedKey.includes('birth')) {
              normalized.dob = cleanVal;
            }
            // 9. Address
            else if (['address', 'village', 'location', 'पता', 'ग्राममोहल्ला', 'पताग्राम', 'निवास'].includes(sanitizedKey) || sanitizedKey.includes('address') || sanitizedKey.includes('village')) {
              normalized.address = cleanVal;
            }
            // 10. Application Date
            else if (['applicationdate', 'applieddate', 'date', 'appdate', 'आवेदनतिथि', 'दिनांक', 'तिथि'].includes(sanitizedKey) || sanitizedKey.includes('date')) {
              normalized.applicationDate = cleanVal;
              normalized.appliedDate = cleanVal;
              normalized.date = cleanVal;
            }
            // 11. Status
            else if (['status', 'currentstatus', 'paymentstatus', 'deliverystatus', 'स्थिति', 'वर्तमानस्थिति'].includes(sanitizedKey) || sanitizedKey.includes('status')) {
              normalized.status = cleanVal;
              normalized.currentStatus = cleanVal;
            }
            // 12. Scheme / Type / Category
            else if (['scheme', 'योजना', 'स्कॉलरशिपयोजना'].includes(sanitizedKey) || sanitizedKey.includes('scheme')) {
              normalized.scheme = cleanVal;
            } else if (['type', 'applicationtype', 'certificatetype', 'servicetype', 'प्रकार', 'आवेदनकाप्रकार'].includes(sanitizedKey) || sanitizedKey.includes('type')) {
              normalized.applicationType = cleanVal;
            } else if (['category', 'वर्ग', 'जातिवर्ग'].includes(sanitizedKey) || sanitizedKey.includes('category')) {
              normalized.category = cleanVal;
            } else if (['subcaste', 'उपजाति'].includes(sanitizedKey)) {
              normalized.subCaste = cleanVal;
            } else if (['amount', 'fee', 'fees', 'शुल्क', 'छात्रवृत्तिराशि', 'income'].includes(sanitizedKey) || sanitizedKey.includes('fee') || sanitizedKey.includes('amount')) {
              normalized.amount = Number(cleanVal) || 0;
              normalized.incomeAmount = Number(cleanVal) || 0;
              normalized.fee = Number(cleanVal) || 0;
            } else {
              normalized[key.trim()] = cleanVal;
            }
          });

          // Secondary pass if applicationNo was not detected by specific keys
          if (!normalized.applicationNo) {
            for (const [k, v] of Object.entries(rawRow)) {
              const kSan = k.toString().trim().toLowerCase().replace(/[^a-z0-9]/g, '');
              if ((kSan.includes('app') || kSan.includes('no') || kSan.includes('num') || kSan.includes('ack') || kSan.includes('ref')) && !['srno', 'sno', 'slno'].includes(kSan)) {
                const valStr = String(v ?? '').trim();
                if (valStr) {
                  normalized.applicationNo = valStr;
                  normalized.applicationNumber = valStr;
                  normalized.appNo = valStr;
                  break;
                }
              }
            }
          }

          // Validation Rules:
          // Must have at least a Name or Applicant Name
          const candidateName = normalized.applicantName || normalized.studentName || normalized.name || rawRow['Name'] || rawRow['नाम'];
          
          if (!candidateName || String(candidateName).trim().length === 0) {
            rejected.push({
              rowNumber: rowNum,
              data: rawRow,
              reason: 'Missing applicant/student name'
            });
          } else {
            // Ensure fallback values
            normalized.applicantName = String(candidateName).trim();
            normalized.studentName = String(candidateName).trim();
            normalized.rawOriginal = rawRow;
            processedRows.push(normalized);
          }
        });

        resolve({
          rows: processedRows,
          rejected,
          detectedColumns
        });
      } catch (err: any) {
        reject(new Error(`Failed to read Excel file: ${err.message || err}`));
      }
    };

    reader.onerror = () => reject(new Error('An error occurred while reading the file'));
    reader.readAsArrayBuffer(file);
  });
}

/**
 * Legacy compatibility aliases for existing modules
 */
export function exportCustomersToExcel(customers: any[]): void {
  const exportData = customers.map((c, i) => ({
    'S.No': i + 1,
    'Customer ID': c.id,
    'Name': c.name,
    'Father Name': c.fatherName || '-',
    'Mobile': c.mobile,
    'Aadhaar': c.aadhaar || '-',
    'DOB': c.dob || '-',
    'Address': c.village || c.address || '-',
    'Total Services': c.totalServicesCount || 0,
    'Registration Date': c.createdAt || '-',
  }));
  exportToExcel(exportData, `CSC_Customers_${new Date().toISOString().slice(0, 10)}`, 'Customers');
}

export function exportCertificatesToExcel(certificates: any[]): void {
  const exportData = certificates.map((cert, i) => ({
    'S.No': i + 1,
    'Application No': cert.applicationNo,
    'Applicant Name': cert.applicantName,
    'Father Name': cert.fatherName || '-',
    'Type': cert.serviceType,
    'Status': cert.status,
    'Mobile': cert.mobile || '-',
    'Application Date': cert.appliedDate || cert.createdAt || '-',
    'Fee': cert.amount || 0,
  }));
  exportToExcel(exportData, `CSC_Certificates_${new Date().toISOString().slice(0, 10)}`, 'Certificates');
}

export function exportTransactionsToExcel(transactions: any[]): void {
  const exportData = transactions.map((tx, i) => ({
    'S.No': i + 1,
    'Receipt / Transaction ID': tx.id,
    'Customer Name': tx.customerName,
    'Mobile': tx.customerMobile || '-',
    'Service Name': tx.serviceName,
    'Category': tx.category || '-',
    'Amount Paid (₹)': tx.amountPaid,
    'Payment Method': tx.paymentMethod,
    'Date & Time': tx.date,
  }));
  exportToExcel(exportData, `CSC_Transactions_${new Date().toISOString().slice(0, 10)}`, 'Transactions');
}

